"""add user role

Revision ID: 65c0eba28bb5
Revises: ac9f208c3b75
Create Date: 2026-09-01 14:59:52.820895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c0eba28bb5'
down_revision: Union[str, Sequence[str], None] = 'ac9f208c3b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
   
    
    user_role_enum = sa.Enum(
        "user",
        "admin",
        name = "userrole"
    )
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False,  server_default="user"))
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    
    user_role_enum = sa.Enum(
        "user",
        "admin",
        name = "userrole"
    )
    
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
