"""add order idempotency key

Revision ID: a1e3e2fa5043
Revises: fc39e37d15d5
Create Date: 2026-09-13 19:29:54.422842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e3e2fa5043'
down_revision: Union[str, Sequence[str], None] = 'fc39e37d15d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('idempotency_key', sa.String(length=36), nullable=False))
    op.create_unique_constraint('uq_orders_user_id_idempotency_key', 'orders', ['user_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_orders_user_id_idempotency_key', 'orders', type_='unique')
    op.drop_column('orders', 'idempotency_key')
    # ### end Alembic commands ###
